# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graffiti.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Graffiti(object):
    def setupUi(self, Graffiti):
        Graffiti.setObjectName(_fromUtf8("Graffiti"))
        Graffiti.resize(800, 600)
        self.centralwidget = QtGui.QWidget(Graffiti)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.BackgroundButton = QtGui.QPushButton(self.centralwidget)
        self.BackgroundButton.setGeometry(QtCore.QRect(0, 10, 121, 24))
        self.BackgroundButton.setObjectName(_fromUtf8("BackgroundButton"))
        self.DMPlotWindow = MatplotlibWidget(self.centralwidget)
        self.DMPlotWindow.setGeometry(QtCore.QRect(320, 0, 361, 351))
        self.DMPlotWindow.setObjectName(_fromUtf8("DMPlotWindow"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(679, 2, 111, 351))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.noll2SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll2SB.setObjectName(_fromUtf8("noll2SB"))
        self.verticalLayout.addWidget(self.noll2SB)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.noll3SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll3SB.setObjectName(_fromUtf8("noll3SB"))
        self.verticalLayout.addWidget(self.noll3SB)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.noll4SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll4SB.setObjectName(_fromUtf8("noll4SB"))
        self.verticalLayout.addWidget(self.noll4SB)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.noll5SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll5SB.setObjectName(_fromUtf8("noll5SB"))
        self.verticalLayout.addWidget(self.noll5SB)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.noll6SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll6SB.setObjectName(_fromUtf8("noll6SB"))
        self.verticalLayout.addWidget(self.noll6SB)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.noll7SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll7SB.setObjectName(_fromUtf8("noll7SB"))
        self.verticalLayout.addWidget(self.noll7SB)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.noll8SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll8SB.setObjectName(_fromUtf8("noll8SB"))
        self.verticalLayout.addWidget(self.noll8SB)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.noll9SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll9SB.setObjectName(_fromUtf8("noll9SB"))
        self.verticalLayout.addWidget(self.noll9SB)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.noll10SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll10SB.setMaximum(10.0)
        self.noll10SB.setSingleStep(0.5)
        self.noll10SB.setObjectName(_fromUtf8("noll10SB"))
        self.verticalLayout.addWidget(self.noll10SB)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 100, 173, 61))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.Gain = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.Gain.setMaximum(1.0)
        self.Gain.setSingleStep(0.05)
        self.Gain.setObjectName(_fromUtf8("Gain"))
        self.horizontalLayout_5.addWidget(self.Gain)
        self.SetGain = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.SetGain.setObjectName(_fromUtf8("SetGain"))
        self.horizontalLayout_5.addWidget(self.SetGain)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.TT_GainSelector = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.TT_GainSelector.setObjectName(_fromUtf8("TT_GainSelector"))
        self.horizontalLayout_6.addWidget(self.TT_GainSelector)
        self.HO_GainSelector = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.HO_GainSelector.setObjectName(_fromUtf8("HO_GainSelector"))
        self.horizontalLayout_6.addWidget(self.HO_GainSelector)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        Graffiti.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Graffiti)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Graffiti.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Graffiti)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Graffiti.setStatusBar(self.statusbar)

        self.retranslateUi(Graffiti)
        QtCore.QMetaObject.connectSlotsByName(Graffiti)

    def retranslateUi(self, Graffiti):
        Graffiti.setWindowTitle(_translate("Graffiti", "MainWindow", None))
        self.BackgroundButton.setText(_translate("Graffiti", "Take Background", None))
        self.label_8.setText(_translate("Graffiti", "Tip n = 2", None))
        self.label_9.setText(_translate("Graffiti", "Tilt n = 3", None))
        self.label.setText(_translate("Graffiti", "Focus n = 4", None))
        self.label_2.setText(_translate("Graffiti", "Astigmatism n = 5", None))
        self.label_3.setText(_translate("Graffiti", "Astigmatism n = 6", None))
        self.label_4.setText(_translate("Graffiti", "Coma n = 7", None))
        self.label_5.setText(_translate("Graffiti", "Coma n = 8", None))
        self.label_6.setText(_translate("Graffiti", "Trefoil n = 9", None))
        self.label_7.setText(_translate("Graffiti", "Trefoil n = 10", None))
        self.SetGain.setText(_translate("Graffiti", "Set Gain", None))
        self.TT_GainSelector.setText(_translate("Graffiti", "Tip/Tilt", None))
        self.HO_GainSelector.setText(_translate("Graffiti", "HODM", None))
        self.pushButton.setText(_translate("Graffiti", "Take Reference Slopes", None))

from GuiTools import MatplotlibWidget
