# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graffiti.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Graffiti(object):
    def setupUi(self, Graffiti):
        Graffiti.setObjectName(_fromUtf8("Graffiti"))
        Graffiti.resize(998, 755)
        self.centralwidget = QtGui.QWidget(Graffiti)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(230, 570, 761, 141))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.TransferFunctionTab = QtGui.QWidget()
        self.TransferFunctionTab.setObjectName(_fromUtf8("TransferFunctionTab"))
        self.pushButton_2 = QtGui.QPushButton(self.TransferFunctionTab)
        self.pushButton_2.setGeometry(QtCore.QRect(589, 10, 131, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.TransferFunctionTab)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 30, 131, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.OpenLoopTF_Filename = QtGui.QLineEdit(self.TransferFunctionTab)
        self.OpenLoopTF_Filename.setGeometry(QtCore.QRect(470, 10, 113, 22))
        self.OpenLoopTF_Filename.setObjectName(_fromUtf8("OpenLoopTF_Filename"))
        self.ClosedLoopFilename = QtGui.QLineEdit(self.TransferFunctionTab)
        self.ClosedLoopFilename.setGeometry(QtCore.QRect(470, 30, 113, 22))
        self.ClosedLoopFilename.setObjectName(_fromUtf8("ClosedLoopFilename"))
        self.pushButton_4 = QtGui.QPushButton(self.TransferFunctionTab)
        self.pushButton_4.setGeometry(QtCore.QRect(570, 70, 161, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tabWidget.addTab(self.TransferFunctionTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(570, 10, 121, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.spinBox = QtGui.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(40, 10, 52, 22))
        self.spinBox.setMaximum(61)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(100, 10, 52, 14))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.lineEdit = QtGui.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(330, 10, 113, 22))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(450, 20, 52, 14))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.spinBox_2 = QtGui.QSpinBox(self.tab_3)
        self.spinBox_2.setGeometry(QtCore.QRect(380, 40, 52, 22))
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(440, 40, 52, 14))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Preset500Hz = QtGui.QPushButton(self.tab_3)
        self.Preset500Hz.setGeometry(QtCore.QRect(620, 10, 90, 23))
        self.Preset500Hz.setObjectName(_fromUtf8("Preset500Hz"))
        self.Preset200Hz = QtGui.QPushButton(self.tab_3)
        self.Preset200Hz.setGeometry(QtCore.QRect(620, 40, 90, 23))
        self.Preset200Hz.setObjectName(_fromUtf8("Preset200Hz"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.HO_IM_Button = QtGui.QPushButton(self.tab)
        self.HO_IM_Button.setGeometry(QtCore.QRect(630, 10, 91, 23))
        self.HO_IM_Button.setObjectName(_fromUtf8("HO_IM_Button"))
        self.TT_IM_Button = QtGui.QPushButton(self.tab)
        self.TT_IM_Button.setGeometry(QtCore.QRect(630, 40, 90, 23))
        self.TT_IM_Button.setObjectName(_fromUtf8("TT_IM_Button"))
        self.Calc_CM_Button = QtGui.QPushButton(self.tab)
        self.Calc_CM_Button.setGeometry(QtCore.QRect(630, 70, 90, 23))
        self.Calc_CM_Button.setObjectName(_fromUtf8("Calc_CM_Button"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 889, 502))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 891, 504))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_7.addWidget(self.pushButton)
        self.RefSlopes_Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.RefSlopes_Button.setObjectName(_fromUtf8("RefSlopes_Button"))
        self.verticalLayout_7.addWidget(self.RefSlopes_Button)
        self.BackgroundButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.BackgroundButton.setObjectName(_fromUtf8("BackgroundButton"))
        self.verticalLayout_7.addWidget(self.BackgroundButton)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.Gain = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.Gain.setMaximum(1.0)
        self.Gain.setSingleStep(0.05)
        self.Gain.setObjectName(_fromUtf8("Gain"))
        self.horizontalLayout_5.addWidget(self.Gain)
        self.SetGain = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.SetGain.setObjectName(_fromUtf8("SetGain"))
        self.horizontalLayout_5.addWidget(self.SetGain)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.TT_GainSelector = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.TT_GainSelector.setObjectName(_fromUtf8("TT_GainSelector"))
        self.horizontalLayout_6.addWidget(self.TT_GainSelector)
        self.HO_GainSelector = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.HO_GainSelector.setObjectName(_fromUtf8("HO_GainSelector"))
        self.horizontalLayout_6.addWidget(self.HO_GainSelector)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.FilterWheelCB = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.FilterWheelCB.setObjectName(_fromUtf8("FilterWheelCB"))
        self.FilterWheelCB.addItem(_fromUtf8(""))
        self.FilterWheelCB.addItem(_fromUtf8(""))
        self.FilterWheelCB.addItem(_fromUtf8(""))
        self.FilterWheelCB.addItem(_fromUtf8(""))
        self.FilterWheelCB.addItem(_fromUtf8(""))
        self.FilterWheelCB.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.FilterWheelCB)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Tip_SpinBox = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.Tip_SpinBox.setMinimum(-1.0)
        self.Tip_SpinBox.setMaximum(1.0)
        self.Tip_SpinBox.setSingleStep(0.01)
        self.Tip_SpinBox.setObjectName(_fromUtf8("Tip_SpinBox"))
        self.horizontalLayout.addWidget(self.Tip_SpinBox)
        self.TipButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.TipButton.setObjectName(_fromUtf8("TipButton"))
        self.horizontalLayout.addWidget(self.TipButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Tilt_SpinBox = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.Tilt_SpinBox.setMinimum(-1.0)
        self.Tilt_SpinBox.setMaximum(1.0)
        self.Tilt_SpinBox.setSingleStep(0.01)
        self.Tilt_SpinBox.setObjectName(_fromUtf8("Tilt_SpinBox"))
        self.horizontalLayout_2.addWidget(self.Tilt_SpinBox)
        self.TiltButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.TiltButton.setObjectName(_fromUtf8("TiltButton"))
        self.horizontalLayout_2.addWidget(self.TiltButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.DMPlotWindow = MatplotlibWidget(self.horizontalLayoutWidget)
        self.DMPlotWindow.setMinimumSize(QtCore.QSize(500, 500))
        self.DMPlotWindow.setMaximumSize(QtCore.QSize(640, 640))
        self.DMPlotWindow.setObjectName(_fromUtf8("DMPlotWindow"))
        self.verticalLayout_5.addWidget(self.DMPlotWindow)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 111, 433))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.noll2SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll2SB.setMaximum(10.0)
        self.noll2SB.setSingleStep(0.01)
        self.noll2SB.setObjectName(_fromUtf8("noll2SB"))
        self.verticalLayout.addWidget(self.noll2SB)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.noll3SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll3SB.setMaximum(10.0)
        self.noll3SB.setSingleStep(0.01)
        self.noll3SB.setObjectName(_fromUtf8("noll3SB"))
        self.verticalLayout.addWidget(self.noll3SB)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.noll4SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll4SB.setMaximum(10.0)
        self.noll4SB.setSingleStep(0.01)
        self.noll4SB.setObjectName(_fromUtf8("noll4SB"))
        self.verticalLayout.addWidget(self.noll4SB)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.noll5SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll5SB.setMaximum(10.0)
        self.noll5SB.setSingleStep(0.01)
        self.noll5SB.setObjectName(_fromUtf8("noll5SB"))
        self.verticalLayout.addWidget(self.noll5SB)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.noll6SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll6SB.setMaximum(10.0)
        self.noll6SB.setSingleStep(0.01)
        self.noll6SB.setObjectName(_fromUtf8("noll6SB"))
        self.verticalLayout.addWidget(self.noll6SB)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.noll7SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll7SB.setMaximum(10.0)
        self.noll7SB.setSingleStep(0.01)
        self.noll7SB.setObjectName(_fromUtf8("noll7SB"))
        self.verticalLayout.addWidget(self.noll7SB)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.noll8SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll8SB.setMaximum(10.0)
        self.noll8SB.setSingleStep(0.01)
        self.noll8SB.setObjectName(_fromUtf8("noll8SB"))
        self.verticalLayout.addWidget(self.noll8SB)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.noll9SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll9SB.setMaximum(10.0)
        self.noll9SB.setSingleStep(0.01)
        self.noll9SB.setObjectName(_fromUtf8("noll9SB"))
        self.verticalLayout.addWidget(self.noll9SB)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.noll10SB = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.noll10SB.setMaximum(10.0)
        self.noll10SB.setSingleStep(0.01)
        self.noll10SB.setObjectName(_fromUtf8("noll10SB"))
        self.verticalLayout.addWidget(self.noll10SB)
        self.UpdateZernButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.UpdateZernButton.setObjectName(_fromUtf8("UpdateZernButton"))
        self.verticalLayout.addWidget(self.UpdateZernButton)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.tab_5)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(20, 90, 160, 129))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.treeView = QtGui.QTreeView(self.verticalLayoutWidget_8)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_8.addWidget(self.treeView)
        self.PixelFileLoad = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.PixelFileLoad.setObjectName(_fromUtf8("PixelFileLoad"))
        self.verticalLayout_8.addWidget(self.PixelFileLoad)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        Graffiti.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Graffiti)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Graffiti.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Graffiti)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Graffiti.setStatusBar(self.statusbar)

        self.retranslateUi(Graffiti)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Graffiti)

    def retranslateUi(self, Graffiti):
        Graffiti.setWindowTitle(_translate("Graffiti", "MainWindow", None))
        self.pushButton_2.setText(_translate("Graffiti", "Measure Open Loop", None))
        self.pushButton_3.setText(_translate("Graffiti", "Measure Closed Loop", None))
        self.pushButton_4.setText(_translate("Graffiti", "Calculate Transfer Function", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TransferFunctionTab), _translate("Graffiti", "Transfer Functions", None))
        self.pushButton_5.setText(_translate("Graffiti", "Measure Latency", None))
        self.label_10.setText(_translate("Graffiti", "Actuator", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Graffiti", "Latency", None))
        self.label_12.setText(_translate("Graffiti", "DIT", None))
        self.label_13.setText(_translate("Graffiti", "NDIT", None))
        self.Preset500Hz.setText(_translate("Graffiti", "500Hz", None))
        self.Preset200Hz.setText(_translate("Graffiti", "200Hz", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Graffiti", "Detector", None))
        self.HO_IM_Button.setText(_translate("Graffiti", "Measure HO IM", None))
        self.TT_IM_Button.setText(_translate("Graffiti", "Measure TT IM", None))
        self.Calc_CM_Button.setText(_translate("Graffiti", "Calculate CM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Graffiti", "Interaction Matrices", None))
        self.pushButton.setText(_translate("Graffiti", "Take Dark", None))
        self.RefSlopes_Button.setText(_translate("Graffiti", "Take Reference Slopes", None))
        self.BackgroundButton.setText(_translate("Graffiti", "Take Background", None))
        self.SetGain.setText(_translate("Graffiti", "Set Gain", None))
        self.TT_GainSelector.setText(_translate("Graffiti", "Tip/Tilt", None))
        self.HO_GainSelector.setText(_translate("Graffiti", "HODM", None))
        self.FilterWheelCB.setItemText(0, _translate("Graffiti", "H+K", None))
        self.FilterWheelCB.setItemText(1, _translate("Graffiti", "ND 1", None))
        self.FilterWheelCB.setItemText(2, _translate("Graffiti", "ND 3", None))
        self.FilterWheelCB.setItemText(3, _translate("Graffiti", "Open", None))
        self.FilterWheelCB.setItemText(4, _translate("Graffiti", "Blank", None))
        self.FilterWheelCB.setItemText(5, _translate("Graffiti", "Initialize", None))
        self.label_11.setText(_translate("Graffiti", "Filter Wheel", None))
        self.TipButton.setText(_translate("Graffiti", "Tip", None))
        self.TiltButton.setText(_translate("Graffiti", "Tilt", None))
        self.label_8.setText(_translate("Graffiti", "Tip n = 2", None))
        self.label_9.setText(_translate("Graffiti", "Tilt n = 3", None))
        self.label.setText(_translate("Graffiti", "Focus n = 4", None))
        self.label_2.setText(_translate("Graffiti", "Astigmatism n = 5", None))
        self.label_3.setText(_translate("Graffiti", "Astigmatism n = 6", None))
        self.label_4.setText(_translate("Graffiti", "Coma n = 7", None))
        self.label_5.setText(_translate("Graffiti", "Coma n = 8", None))
        self.label_6.setText(_translate("Graffiti", "Trefoil n = 9", None))
        self.label_7.setText(_translate("Graffiti", "Trefoil n = 10", None))
        self.UpdateZernButton.setText(_translate("Graffiti", "Update", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Graffiti", "Tab 1", None))
        self.PixelFileLoad.setText(_translate("Graffiti", "Load Pixel File", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Graffiti", "Tab 2", None))

from GuiTools import MatplotlibWidget
